enum ErrorContext {
    CONTEXT_SUCCESS = 10,
    CONTEXT_FONT_MISSING = 11,
    CONTEXT_VECTOR_INIT_FAILED = 12,
    CONTEXT_DATA_INIT_FAILED = 13,
};

enum ErrorGame {
    GAME_SUCCESS = 20,
    GAME_FONT_MISSING = 21,
    GAME_RES_MISSING = 22,
};

enum ErrorVector {
    VECTOR_SUCCESS = 30,
    VECTOR_NULL_POINTER = 31,
    VECTOR_MEMORY_ALLOCATION = 32,
    VECTOR_INDEX_OUT_OF_BOUNDS = 33,
    VECTOR_UNINITIALIZED = 34,
    VECTOR_DESTROY_FAILED = 35,
};

enum ErrorData {
    DATA_SUCCESS = 40,
    DATA_DIR_EMPTY = 41,
    DATA_FILE_NOT_FOUND = 42,
    DATA_INVALID_FORMAT = 43,
    DATA_LINE_TOO_LONG = 44,
    DATA_LINE_EMPTY = 45,
    DATA_ALLOCATION_FAILED = 46,
};

enum ErrorTexture {
    TEXTURE_SUCCESS = 50,
    TEXTURE_FILE_NOT_FOUND = 51,
};