enum ErrorContext {
    CONTEXT_SUCCESS,
    CONTEXT_FONT_MISSING,
};

enum ErrorGame {
    GAME_SUCCESS,
    GAME_FONT_MISSING,
    GAME_RES_MISSING
};

enum ErrorVector {
    VECTOR_SUCCESS,
    VECTOR_NULL_POINTER,
    VECTOR_MEMORY_ALLOCATION,
    VECTOR_INDEX_OUT_OF_BOUNDS,
    VECTOR_UNINITIALIZED,
};

enum ErrorData {
    DATA_SUCCESS,
    DATA_DIR_EMPTY,
    DATA_FILE_NOT_FOUND,
    DATA_INVALID_FORMAT,
    DATA_LINE_TOO_LONG,
    DATA_LINE_EMPTY,
};